# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, devel]


name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: print repo name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     use-public-rspm: true
      #
      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check

      # - uses: r-lib/actions/check-r-package@v2
