# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]

name: Sweave2rmd

jobs:
  fetch-check-repo:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - name: create repo
        run: |
          echo $REPO_NAME
          git clone "https://git.bioconductor.org/packages/$REPO_NAME"
          rm -rf $REPO_NAME/.git*
          mv $REPO_NAME/* .
          rm -rf $REPO_NAME
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: LiNk-NY/Rnw2Rmd
      - name: convert Rnw
        run: |
          R -e 'setwd("vignettes")
                 for (fname in list.files(path = ".", pattern = "\\.rnw$", ignore.case = TRUE)){
                  try(Rnw2Rmd::Rnw2Rmd(from = fname, to = sub("rnw", "Rmd", x = fname, ignore.case = TRUE), validate = FALSE))
                 }'
      - name: git add
        run: |
          git config --global --add safe.directory /__w/$REPO_NAME/$REPO_NAME
          git config user.name helpful-bot
          git config user.email github-actions@github.com
          git add *
          git rm .github/workflows/Sweave2rmd.yaml
          git commit -am "PR autogenerated by Sweave2rmd.yaml"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
